#!/usr/bin/env python
import os
import subprocess
import fnmatch

rootdir = '/var/www'
config = 'wp-config.php'
webdir = 'web'
wpdir = []

for root, dirnames, filenames in os.walk(rootdir):
    for filename in fnmatch.filter(filenames, config):
        if os.path.split(root)[1] == webdir:
            wpdir.append(os.path.join(root))

for dir in wpdir:
    p = subprocess.Popen("cd %s; wp --allow-root plugin status | grep -e '^ U' | grep -v Legend | awk {'print $2'}" % dir, shell=True, stdout=subprocess.PIPE)
    plugin_list, err = p.communicate()
    if plugin_list:
        print dir
    for plugin in plugin_list.split():
        print plugin
